name: Generate sitemap

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 UTC
    - cron: '0 12 * * *'  # 매일 오후 9시 UTC
  workflow_dispatch:     # 수동 실행도 가능하게

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate sitemap.xml
        run: python sitemap_generator.py

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap.xml"
          git push
